version: '3.1'
services:
  postgresql:
    image: postgres:10.4
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_db
  api:
    restart: always    
    container_name: api
    image: imagem-api
    build:
      context: api
      dockerfile: DockerFile      
    ports:
      - 8180:8180
    depends_on:
      - postgresql
  client:
    restart: always
    container_name: client
    image: imagem-client
    build:
      context: client
      dockerfile: DockerFile
    ports:
      - 8080:8080
    depends_on:
      - api